### ISSUE TITLE
Install and run docker_gc as part of recipe

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/chef_chatops_deployer#5]

**Comment by emilsoman** [comment]
@ganeshmannamal want to give this a try ? You can follow the instructions here : https://github.com/code-mancers/chatops_deployer#server-setup (See the last point about docker-gc)

**Comment by ganeshmannamal** [comment]
Surely would love to work on this.

**Comment by emilsoman** [comment]
Fixed by #7
